In [37]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
train = pd.read_csv("/content/drive/MyDrive/ml_dataset/train.csv")
meal = pd.read_csv("/content/drive/MyDrive/ml_dataset/meal_info.csv")
center = pd.read_csv("/content/drive/MyDrive/ml_dataset/fulfilment_center_info.csv")

In [4]:
df = pd.read_csv("/content/drive/MyDrive/ml_dataset/train.csv")
df.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders
0,1379560,1,55,1885,136.83,152.29,0,0,177
1,1466964,1,55,1993,136.83,135.83,0,0,270
2,1346989,1,55,2539,134.86,135.86,0,0,189
3,1338232,1,55,2139,339.50,437.53,0,0,54
4,1448490,1,55,2631,243.50,242.50,0,0,40

In [5]:
df = pd.read_csv("/content/drive/MyDrive/ml_dataset/meal_info.csv")
df.head()

   meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai
3     1248  Beverages  Indian
4     2631  Beverages  Indian

In [6]:
df = pd.read_csv("/content/drive/MyDrive/ml_dataset/fulfilment_center_info.csv")
df.head()

   center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   center_id    77 non-null     int64
 1   city_code    77 non-null     int64
 2   region_code  77 non-null     int64
 3   center_type  77 non-null     object
 4   op_area      77 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 3.1+ KB

In [8]:
df.head()

   center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [9]:
print(df)

    center_id  city_code  region_code center_type  op_area
0          11        679           56      TYPE_A      3.7
1          13        590           56      TYPE_B      6.7
2         124        590           56      TYPE_C      4.0
3          66        648           34      TYPE_A      4.1
4          94        632           34      TYPE_C      3.6
..        ...        ...          ...         ...      ...
72         53        590           56      TYPE_A      3.8
73         30        604           56      TYPE_A      3.5
74         76        614           85      TYPE_A      3.0
75         68        676           34      TYPE_B      4.1
76         51        638           56      TYPE_A      7.0

[77 rows x 5 columns]

In [10]:
df.shape

(77, 5)

In [11]:
df.describe()

        center_id   city_code  region_code    op_area
count   77.000000   77.000000    77.000000  77.000000
mean    83.142857  600.662338    56.493506   3.985714
std     46.090219   66.720274    18.126473   1.106406
min     10.000000  456.000000    23.000000   0.900000
25%     50.000000  553.000000    34.000000   3.500000
50%     77.000000  596.000000    56.000000   3.900000
75%    110.000000  651.000000    77.000000   4.400000
max    186.000000  713.000000    93.000000   7.000000

In [12]:
df.columns

Index(['center_id', 'city_code', 'region_code', 'center_type', 'op_area'], dtype='object')

In [13]:
#Data Cleaning: Output "True" --> means that there are some null values
df.isnull().any().any()

np.False_

In [14]:
df.isnull().sum()

center_id      0
city_code      0
region_code    0
center_type    0
op_area        0
dtype: int64

In [15]:
#Print the rows with missing values.
df[df.isnull().any(axis = 1)]

Empty DataFrame
Columns: [center_id, city_code, region_code, center_type, op_area]
Index: []

In [31]:
if 'number' in df.columns:
    del df['number']

In [21]:
df.shape

(77, 5)

In [22]:
before_rows = df.shape[0]
df = df.dropna()
after_rows = df.shape[0]

print("Before rows: ", before_rows)
print("After rows: ", after_rows)
print("The number of dropped rows are: ", before_rows - after_rows)
#print("The number of dropped rows are ()".format(before_rows - after_rows))

Before rows:  77
After rows:  77
The number of dropped rows are:  0

In [23]:
df.shape

(77, 5)

In [34]:
data = train.merge(meal, on="meal_id")
data = data.merge(center, on="center_id")

In [35]:
data['demand'] = data['num_orders'].apply(lambda x: 1 if x > 100 else 0)

In [25]:
clean_data.columns

Index(['center_id', 'city_code', 'region_code', 'center_type', 'op_area'], dtype='object')

In [26]:
clean_data.shape

(77, 5)

In [36]:
# correct approach
data = train.merge(meal, on="meal_id")
data = data.merge(center, on="center_id")

data['demand'] = data['num_orders'].apply(lambda x: 1 if x > 100 else 0)

data = pd.get_dummies(data)

In [28]:
clean_data.shape

(77, 5)

In [29]:
##Split dataset into independent and dependant features.
X=clean_data.iloc[:,:-1]
print(X)

    center_id  city_code  region_code center_type
0          11        679           56      TYPE_A
1          13        590           56      TYPE_B
2         124        590           56      TYPE_C
3          66        648           34      TYPE_A
4          94        632           34      TYPE_C
..        ...        ...          ...         ...
72         53        590           56      TYPE_A
73         30        604           56      TYPE_A
74         76        614           85      TYPE_A
75         68        676           34      TYPE_B
76         51        638           56      TYPE_A

[77 rows x 4 columns]

In [48]:
y=clean_data.iloc[:,-1]
print(y)

0     3.7
1     6.7
2     4.0
3     4.1
4     3.6
     ...
72    3.8
73    3.5
74    3.0
75    4.1
76    7.0
Name: op_area, Length: 77, dtype: float64